#! /bin/sh
bspc config border_width         	1
bspc config active_border_color		"#0c0b0a"
bspc config normal_border_color		"#0c0b0a"
bspc config focused_border_color	"#0c0b0a"
bspc config urgent_border_color		"#0c0b0a"
bspc config presel_border_color		"#0c0b0a"
bspc config window_gap          	17
bspc config split_ratio          	0.381966
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
