#! /bin/sh
bspc config border_width         	1
bspc config active_border_color		"#0f0705"
bspc config normal_border_color		"#0f0705"
bspc config focused_border_color	"#0f0705"
bspc config urgent_border_color		"#0f0705"
bspc config presel_border_color		"#0f0705"
bspc config window_gap          	11
bspc config split_ratio          	0.309017
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
